site_name: Multi-Indicator, Small Area Estimation Resource
site_url: http://sae4healthGates.com
theme:
  name: material
  custom_dir: overrides/landing_page

  features:
  - navigation.indexes
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.tracking
  - navigation.top
  - navigation.instant
  - navigation.instant.progress
  - search.highlight
  - search.share
  - search.suggest

extra:
  hide:
    - toc


nav:
  - Home: index.md
  - Nigeria: 
    - Overview: country_selection/Nigeria/nigeria.md
    - DTP 3 Vaccination: country_selection/Nigeria/CH_VACC_C_DP3.md
    - MCV 1 Vaccination: country_selection/Nigeria/CH_VACC_C_MSL.md
    - Received No Vaccination: country_selection/Nigeria/CH_VACC_C_NON.md
    - Stunting Rate: country_selection/Nigeria/CN_NUTS_C_HA2.md
    - Child Wasting: country_selection/Nigeria/CN_NUTS_C_WH2.md
    - Women with Mobile Phone: country_selection/Nigeria/CO_MOBB_W_MOB.md
    - Women with Secondary+ Education: country_selection/Nigeria/ED_EDUC_W_SEH.md
    - Women Literate: country_selection/Nigeria/ED_LITR_W_LIT.md
    - Modern Contraceptive Rate: country_selection/Nigeria/FP_EVUM_W_MOD.md
    - Population in Lowest two Wealth Quintiles: country_selection/Nigeria/HC_WIXQ_P_12Q.md
    - Children slept under ITN: country_selection/Nigeria/ML_NETC_C_ITN.md
    - 4+ ANC Visits: country_selection/Nigeria/RH_ANCN_W_N4P.md
    - Delivery by Skilled Provider: country_selection/Nigeria/RH_DELA_C_SKP.md
    - Delivery in Health Facility: country_selection/Nigeria/RH_DELP_C_DHT.md
  - Rwanda: 
    - Overview: country_selection/rwanda.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html

extra_css:
  - assets/stylesheets/custom.css
  - overrides/extra.css
  - stylesheets/extra.css